---

- name: Update package repos
  apt:
    update_cache: yes

- name: Developer group
  group:
    name: developer
    state: present

- name: Create User Logins
  user:
    name: "{{ item.username }}"
    comment: "{{ item.name }}"
    groups: developer
    state: present
    shell: /bin/bash
    append: yes
  with_items: "{{ user_config }}"
  changed_when: no

- name: Make Vagrant login shell bash
  user:
    name: vagrant
    shell: /bin/bash
  when: '"local_vagrant" in inventory_dir'

- name: Add SSH key authorization
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.sshkey }}"
  with_items: "{{ user_config }}"


- name: Install basic dev util packages
  apt:
    pkg:
      - vim
      - htop
      - jq
      - net-tools
      - unzip
      - cifs-utils
      - mysql-client
    state: latest
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success